### ISSUE TITLE
Please offer compiled binaries for Windows, etc.

### ISSUE THREAD

**Issue by Zero3K** [giannitedesco/project-mayhem#1] opened 2015-03-12 03:20 UTC
*subject*

Thanks in advance.

**Comment by giannitedesco** [comment] 2015-03-12 06:46
It should compile relatively cleanly under mingw, it needs os-posix.c re-implemented for windows with a little bit of winsock glue.

Unfortunately I don't really have the time for this (or much other unpaid work at all) right now. Also, I suspect the streamate protocol has probably moved along somewhat and the code will need updating in general.

**Comment by Zero3K** [comment] 2015-03-12 07:32
I don't think it changed that much. I and another guy tried compiling it but ran into some errors (such as needing hgang.c, etc. along with the syntax not being correct). Do you still have any of the binaries you compiled earlier?

**Comment by giannitedesco** [comment] 2015-03-12 08:20
Pushed an update which should fix compile issues.

**Comment by Zero3K** [comment] 2015-03-12 16:00
This is what is now happening when compiling it using Portable Ubuntu via coLinux:

pubuntu@pubuntu:~/Desktop/project-mayhem-master$ make
 [C] blob.c
 [C] os-posix.c
 [C] amf3.c
 [C] amf.c
 [C] hexdump.c
 [C] nbio.c
 [C] nbio-connecter.c
 [C] nbio-listener.c
 [C] nbio-epoll.c
 [C] nbio-poll.c
 [C] cvars.c
 [C] netstatus.c
 [C] rtmp.c
 [C] flv.c
 [C] mayhem.c
 [C] mayhem-amf.c
 [C] dump.c
 [LINK] wmdump
 [C] amfparse.c
 [LINK] amfparse
 [C] hgang.c
hgang.c:11:19: warning: hgang.h: No such file or directory
hgang.c:36: error: expected ‘)’ before ‘h’
hgang.c:80: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘hgang_new’
hgang.c:158: error: expected ‘)’ before ‘h’
hgang.c:188: error: expected ‘)’ before ‘h’
hgang.c:213: error: expected ‘)’ before ‘h’
hgang.c:233: error: expected ‘)’ before ‘h’
hgang.c:255: error: expected ‘)’ before ‘h’
make: *** [hgang.o] Error 1

**Comment by Zero3K** [comment] 2015-03-12 16:15
Trying to compile it using TDM-GCC (http://tdm-gcc.tdragon.net/) results in this:

C:\Users\Bryan\Desktop\project-mayhem-master>mingw32-make
" [C] os-posix.c"
In file included from os-posix.c:6:0:
include/os.h:9:9: error: unknown type name 'SOCKET'
 typedef SOCKET os_sock_t;
         ^
os-posix.c:8:24: fatal error: sys/socket.h: No such file or directory
 #include <sys/socket.h>
                        ^
compilation terminated.
Makefile:146: recipe for target 'os-posix.o' failed
mingw32-make: *** [os-posix.o] Error 1

**Comment by Zero3K** [comment] 2015-03-12 20:19
I just tried to compile it using Cygwin. Here's a link to the errors I received when doing so:

http://pastebin.com/igaFzsxb

**Comment by Leifman27** [comment] 2015-03-12 21:37
if its compiled successfully for windows, i'd really appreciate it if someone can upload the compiled version somewhere for common plebs that aren't so familiar to compiling etc'

**Comment by Zero3K** [comment] 2015-03-13 06:53
Btw, will this program allow the viewing of Private Sessions?

**Comment by giannitedesco** [comment] 2015-03-13 06:59
I pushed another change to fix the linux compile issues.

I never got paid/private stuff working. It costs money to experiment with and reverse engineer that stuff. So I didn't get around to it. Although it's kind of close.

The windows compile issue is that windows.h needs to be included, and all the functions in os-posix.c need to be re-implemented for windows.

**Comment by Zero3K** [comment] 2015-03-13 07:07
What do you mean by "kind of close"?

**Comment by giannitedesco** [comment] 2015-03-13 07:08
I just mean, no pre-requisites needed, you can just go ahead and implement the relevant message types.

**Comment by Zero3K** [comment] 2015-03-13 07:22
Now I'm getting these errors when compiling it via Portable Ubuntu via coLinux:

 [C] blob.c
 [C] os-posix.c
 [C] amf3.c
 [C] amf.c
 [C] hexdump.c
 [C] nbio.c
 [C] nbio-connecter.c
 [C] nbio-listener.c
In file included from nbio-listener.c:14:
/usr/include/linux/netfilter_ipv4.h:53: error: ‘INT_MIN’ undeclared here (not in a function)
/usr/include/linux/netfilter_ipv4.h:64: error: ‘INT_MAX’ undeclared here (not in a function)
make: *** [nbio-listener.o] Error 1

**Comment by giannitedesco** [comment] 2015-03-13 07:30
Fixed. Well, worked around, the error is in their kernel headers package.

**Comment by Zero3K** [comment] 2015-03-13 07:48
Now it compiles with no errors. I tried compiling wmcleint by running its script. It gave me the following errors:

mport: unable to open image `pymayhem': Is a directory @ blob.c/OpenBlob/2480.
from: can't read /var/mail/collections
from: can't read /var/mail/time
./wmclient: 12: class: not found
./wmclient: 13: Syntax error: "(" unexpected

**Comment by giannitedesco** [comment] 2015-03-13 07:54
Erm. No idea what went wrong there, it's just a python script.

Try: python wmclient

**Comment by Zero3K** [comment] 2015-03-14 18:25
I can't get it to run. Please compile them so I and others can run them without having to get our hands dirty.

**Comment by giannitedesco** [comment] 2015-03-14 18:32
You already compiled it. The problem is that your shell or python (interpreted languages) environments are not working. I cannot fix that without more info. And honestly the problem looks like python isn't even running. Just type python ./wmclient - what happened?

This is not release/production software. It's open source hobbyist software, which is incomplete. And of basically of little to no interest to non-programmers, since it's unfinished, experimental, and nobody is paid to support it.

And where should I host the compiled binaries? Possibly including malware :P

**Comment by Zero3K** [comment] 2015-03-14 18:36
1\* This is what happens when I try to run it now (in Portable Ubuntu):

Traceback (most recent call last):
  File "./wmclient", line 4, in <module>
    import mayhem
ImportError: No module named mayhem

2\* You can upload them here to a /bin/ directory.

**Comment by giannitedesco** [comment] 2015-03-14 18:39
Which won't fix your problem since python is an interpreted language.

$ make mayhem.so

did your previous make run even succeed? is python-dev installed?

**Comment by giannitedesco** [comment] 2015-03-14 18:41
And for which version of python should I compile the python extensions? which OS? how often should I update them to respond to further issues with binary compatibility? :)

You see, software development is time-consuming and expensive, heh.

**Comment by Zero3K** [comment] 2015-03-14 19:21
I managed to get wmclient to load. But, it doesn't display a model's stream. Here's the errors it gave me:

conn: webcammayhem.com None
conn: m2.nsimg.net None
conn: m1.nsimg.net None
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/home/pubuntu/Desktop/project-mayhem-master/pymayhem/webthread.py", line 35, in run
    self._do_work(work)
  File "/home/pubuntu/Desktop/project-mayhem-master/pymayhem/webthread.py", line 72, in _do_work
    req.cb(r, d)
  File "/home/pubuntu/Desktop/project-mayhem-master/pymayhem/webthread.py", line 125, in Closure
    cb(h.result, url)
  File "./wmclient", line 387, in got_vars
    v = self.convert(d, url)
  File "./wmclient", line 355, in convert
    v.sid = int(d['p_sid'])
KeyError: 'p_sid'

**Comment by giannitedesco** [comment] 2015-03-14 19:29
Like I said, it's probably changed in the last few years..

**Comment by Zero3K** [comment] 2015-03-14 19:32
Btw, here's a ZIP of the source, object files, and binaries (that are compiled for Ubuntu v10.04 and up):

http://d-h.st/OOgx

**Comment by giannitedesco** [comment] 2015-03-14 19:35
Thanks

**Comment by giannitedesco** [comment] 2015-03-14 19:36
Closing because compile issues seem resolved. You might want to open another to track that the HTML has changed in the last year or 2 causing web scraping to fail.

**Closed by giannitedesco** 2015-03-14 19:36 UTC
